apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata: 
  name: mlops-api-PodMonitoring
  namespace: default
spec:
  selector: 
    matchLabels: 
      app: mlops-api
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s