apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-web-deployment
  labels:
    app: mlops-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-web
  template:
    metadata:
      labels:
        app: mlops-web
    spec:
      containers:
      - name: mlops-web
        image: gcr.io/mlops-476106/mlops-web:latest # <--- Reemplaza con la ruta de tu imagen
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: "http://mlops-api-service:5000/predict"